/*

 BLACK_BG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\jacob\OneDrive\Desktop\Game Project\castle_2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define black_bgWidth 20
#define black_bgHeight 18
#define black_bgBank 0

extern unsigned char black_bg[];

/* End of BLACK_BG.H */
