/*

 BOOK.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 12
   Tile set      : C:\Users\jacob\OneDrive\Desktop\Game Project\book_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 46
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bookWidth 20
#define bookHeight 12
#define bookBank 0

extern unsigned char book[];

/* End of BOOK.H */
