/*

 CASTLE_BG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : C:\Users\jacob\OneDrive\Desktop\Game Project\castle_2.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define castle_bgWidth 32
#define castle_bgHeight 32
#define castle_bgBank 0

extern unsigned char castle_bg[];

/* End of CASTLE_BG.H */
