/*

 ENTRY_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 12
   Tile set      : C:\Users\jacob\OneDrive\Desktop\Game Project\entry_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 46
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define entry_mapWidth 20
#define entry_mapHeight 12
#define entry_mapBank 0

extern unsigned char entry_map[];

/* End of ENTRY_MAP.H */
